#ifndef STDAFX_H
#define STDAFX_H

#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QAction>
#include <QPushButton>
#include <QTextEdit>
#include <QVBoxLayout>
#include <QJsonDocument>
#include <QJsonObject>
#include <QJsonArray>
#include <QFile>
#include <QTextStream>
#include <QMessageBox>
#include <QDir>
#include <QLabel>
#include <QComboBox>
#include <QListView>
#include <QCheckBox>
#include <QHBoxLayout>
#include <QVector>
#include <QListWidget>
#include <QString>
#include <QDialog>
#include <QIcon>
#include <QStringList>
#include <QClipboard>
#include <QApplication>
#include <QNetworkInterface>
#include <QSysInfo>
#include <QDateTime>
#include <QFileDialog>
#include <QPixmap>
#include <QFrame>
#include <QTabWidget>
#include <QPainter>
#include <QPen>

#endif // STDAFX_H